theme: jekyll-theme-cayman
title: "RoboSoft'25: The 1st International Workshop on Vision-Language in Soft Robot"
highlighter: rouge
description:
- ACM Multimedia 2025 Workshop
- October 28, 2025
- Dublin, Ireland

buttons:
  Overview: './index.html'
  Schedule: './schedule.html'
  Call for Papers: './call4papers.html'
  Challenge: './challenge.html'


nav:
  - title: Overview
    url: './index.html'
    subnav:
      - title: 'Invited Speakers'
        url: './index.html#invited-speakers'
      - title: 'Call for Papers'
        url: './index.html#call-for-papers'
      - title: 'Challenge'
        url: './index.html#challenge'
      - title: 'Important Dates'
        url: './index.html#important-dates'
      - title: 'Program Committee'
        url: './index.html#program-committee'
      - title: 'Challenge Technical Committee'
        url: './index.html#challenge-technical-committee'
      
  - title: Schedule
    url: './schedule.html'
  - title: Call for Papers
    url: './call4papers.html'
  - title: Challenge
    url: './challenge.html'
    subnav:
      - title: 'Leaderboard'
        url: './challenge.html#leaderboard'
      - title: 'Data Details'
        url: './challenge.html#data-details'
      - title: 'Codebase'
        url: './challenge.html#codebase'
      - title: 'Development Toolkit'
        url: './challenge.html#development-toolkit'

github:
  is_project_page: false
